services:
  wa_gateway_prod:
    build:
      context: ./wa-gateway
      dockerfile: ./Dockerfile
    ports:
      - "80:8000"

  wa_gateway_dev:
    build:
      context: ./wa-gateway
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: fastapi dev src/main.py --host 0.0.0.0
    volumes:
      - ./wa-gateway/src:/app/src